---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - ubuntu-restricted-extras
        - htop
        - git
        - build-essential

  - name: install snaps
    snap:
      name:
        - chromium
        - code
        - bashtop
