---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: add megasync repository
    apt_repository:
      repo: deb https://mega.nz/linux/MEGAsync/xUbuntu_20.04/ ./
      state: present
      update_cache: true

  - name: add R repository key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: E298A3A825C0D65DFD57CBB651716619E084DAB9

  - name: add R repository
    apt_repository:
      repo: deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/
      state: present
      update_cache: true

  - name: install packages
    package:
      name:
        - python3-psutil
        - python3-pip
        - python3-venv
        - gnome-shell-extensions
        - gnome-tweaks
        - build-essential
        - docker.io
        - emacs
        - vim
        - steam
        - megasync
        - r-base
        - r-base-dev
        - ess
        - jupyter
        - texlive-full

  - name: install snaps
    snap:
      name:
        - chromium
        - zoom-client
        - bashtop

  - name: install vscode
    snap:
      name: code
      classic: yes

  - name: add user to docker group
    user:
      name: lab
      groups: docker
      append: yes

  - name: set night-light-enabled
    become_user: lab
    dconf:
      key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
      value: "true"

  - name: set desktop clock-format
    become_user: lab
    dconf:
      key: "/org/gnome/desktop/interface/clock-format"
      value: "'12h'"

  - name: set desktop clock-show-seconds
    become_user: lab
    dconf:
      key: "/org/gnome/desktop/interface/clock-show-seconds"
      value: "true"

  - name: set 12 hour clock show-date
    become_user: lab
    dconf:
      key: "/org/gnome/desktop/interface/clock-show-date"
      value: "true"

  - name: set 12 hour clock show-weekday
    become_user: lab
    dconf:
      key: "/org/gnome/desktop/interface/clock-show-weekday"
      value: "true"

  - name: set applications dark mode
    become_user: lab
    dconf:
      key: "/org/gnome/desktop/interface/gtk-theme"
      value: "'Yaru-dark'"

  - name: set gnome shell dark mode
    become_user: lab
    dconf:
      key: "/org/gnome/shell/extensions/user-theme/name"
      value: "'Yaru-dark'"

  - name: set desktop background primary-color
    become_user: lab
    dconf:
      key: "/org/gnome/desktop/background/primary-color"
      value: "'black'"

  - name: set desktop background secondary-color
    become_user: lab
    dconf:
      key: "/org/gnome/desktop/background/secondary-color"
      value: "'black'"

  - name: set desktop background color-shading-type
    become_user: lab
    dconf:
      key: "/org/gnome/desktop/background/color-shading-type"
      value: "'solid'"

  - name: set desktop background picture-options
    become_user: lab
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'none'"

  - name: set desktop background picture-uri
    become_user: lab
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "''"
